config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations, controllers: {
                       sessions: "users/sessions",
                       passwords: "users/passwords",
                     }

  root "home#index"

  devise_scope :user do
    get "users/edit" => "users/registrations#edit", :as => "edit_user_registration"
    put "user" => "users/registrations#update", :as => "user_registration"
  end

  # Ruta para suscribirle a los newsletter

  resources :subscriptions, only: [:new, :create]

  scope :guests, as: :guests do
    get :new, to: "guests#new"
    post :create, to: "guests#create"
    # resources :subscriptions, controller: "guests", only: [:new, :create], as: :guest
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def new
  end

  def create
    @subscription = Subscription.new(subscription_params)
    @email = subscription_params[:email]
    @user = User.find_by(email: @email)

    categories = params[:subscription][:category_ids].reject(&:empty?)

    if @user.nil?
      new_password = Devise.friendly_token.first(10)
      @user = User.new
      @user.password = new_password
      @user.email = @email
      if @user.save
        begin
          @subscription.user = @user
          @subscription.save!
          categories.each do |c|
            sc = SubscriptionCategory.new
            sc.subscription = @subscription
            sc.category_id = c.to_i
            sc.save
          end
          redirect_to root_path, notice: t(:notice_subscription)
          SubscriptionJob.perform_later(@subscription)
          sign_in @user
        rescue ActiveRecord::RecordInvalid => invalid
          redirect_to guests_new_path, alert: invalid.record.errors.full_messages[0]
        end
      end
      # si se encuentra el email
    else
      redirect_to new_user_session_path
    end
  end

  private

  def subscription_params
    params.require(:subscription).permit(:email)
  end
end

app/views/guests/_form.html.erb
  <!-- ============================================================== -->
<!-- pageheader  -->
<!-- ============================================================== -->
<div class="row">
  <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
    <div class="page-header">
      <h2 class="pageheader-title">E-commerce Product Checkout </h2>
      <p class="pageheader-text">Nulla euismod urna eros, sit amet scelerisque torton lectus vel mauris facilisis faucibus at enim quis massa lobortis rutrum.</p>
      <div class="page-breadcrumb">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">E-coommerce</a></li>
            <li class="breadcrumb-item active" aria-current="page">E-Commerce Product Checkout</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<!-- ============================================================== -->
<!-- end pageheader  -->
<!-- ============================================================== -->
<div class="row">
  <div class="offset-xl-2 col-xl-8 col-lg-12 col-md-12 col-sm-12 col-12">
    <div class="row">
      <div class="col-md-8">
        <div class="card">
          <div class="card-body text-center">
            <%= t(:presentation) %>
          </div>
          <%= form_tag guests_create_path, id:"form-subscription" do %>
            <div class="card-body">
              <div class="row">
                <div class="col-md-12 mb-3">
                  <%= label_tag :email%>
                  <%= email_field_tag "subscription[email]",nil, class:"form-control", required: true %>
                </div>
              </div>
            </div>
            <div class="card-body border-top">
              <h5><%= t("preferences") %></h5>
              <%= collection_check_boxes(:subscription, :category_ids, Category.all, :id, :name ) do |b| %>
                <div class="custom-control custom-checkbox">
                  <%=  b.label(:"data-value" => b.value) { b.check_box + b.text } %>
                </div>
              <% end %>
            </div>
            <hr class="mb-4">
            <%= button_tag type: 'submit', class:"btn btn-success btn-block", id:"cmd_save" do %>
              <i class="far fa-paper-plane"></i> <%= t(:subscribe)%>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(function(){
    var form = $("#form-subscription")
    form.validate({
      errorClass: "text-danger",
      rules: {
        "subscription[email]": {
          required: true,
          email: true
        },
         'subscription[category_ids][]': {
        required: true
        }
      },
      messages:{
          "subscription[email]": {
          required: "Ingrese su correo electrónico",
          email: "Formato de correo inválido"
        },
        'subscription[category_ids][]': "Debes seleccionar una categoría"
      },
       errorPlacement: function (error, element) {
            if (element.attr("type") == "checkbox") {
                 $.notify("Debes seleccionar una categoría", "warn");
            } else {
                  $(element).after(error);
            }
        }
    })
  })
</script>

app/views/guests/_show_subscriptions.html.erb
<div class="col-md-4 mb-4">
  <div class="card">
    <div class="card-header">
      <h4 class="d-flex justify-content-between align-items-center mb-0">
        <span class="text-muted"><%= t("your_subscriptions")%></span>
        <span class="badge badge-secondary badge-pill"><%= current_user.subscriptions.count %></span>
      </h4>
    </div>
    <div class="card-body">
      <ul class="list-group mb-3">
        <% current_user.subscriptions.each do |item| %>
          <li class="list-group-item d-flex justify-content-between">
            <div>
              <h6 class="my-0"><%= item.category.name %></h6>
              <small class="text-muted"><%= t("product_available")%></small>
            </div>
            <span class="text-muted"><%= number_with_delimiter(rand(230..15000)) %></span>
          </li>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/guests/new.html.erb
<%= render 'form', subscription: @subscription %>