config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations, controllers: {
                       sessions: "users/sessions",
                       passwords: "users/passwords",
                     }

  root "home#index"

  devise_scope :user do
    get "users/edit" => "users/registrations#edit", :as => "edit_user_registration"
    put "user" => "users/registrations#update", :as => "user_registration"
  end

  # Ruta para suscribirle a los newsletter

  resources :subscriptions, only: [:new, :create]

  scope :guests, as: :guests do
    get :new, to: "guests#new"
    post :create, to: "guests#create"
    # resources :subscriptions, controller: "guests", only: [:new, :create], as: :guest
  end
end

app/models/subscription.rb
# == Schema Information
#
# Table name: subscriptions
#
#  id         :integer          not null, primary key
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
# Indexes
#
#  index_subscriptions_on_email    (email)
#  index_subscriptions_on_user_id  (user_id)
#

include EmailValidate

class Subscription < ApplicationRecord
  belongs_to :user

  validates_uniqueness_of :user_id
  validates :email, presence: true, length: { maximum: 60 },
                    uniqueness: { case_sensitive: false, with: URI::MailTo::EMAIL_REGEXP }

  has_many :subscription_categories, dependent: :destroy

  # valida el email
  # https://www.abstractapi.com/email-verification-validation-api
  # sólo para los modelos que tengan el campo email
  validate :validate_email_api
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    @subscription = Subscription.new(subscription_params)
    @subscription.user = current_user
    categories = params[:subscription][:category_ids].reject(&:empty?)

    begin
      @subscription.save!
      categories.each do |c|
        sc = SubscriptionCategory.new
        sc.subscription = @subscription
        sc.category_id = c.to_i
        sc.save
      end
      redirect_to root_path, notice: t(:notice_subscription)
      SubscriptionJob.perform_later(@subscription)
    rescue ActiveRecord::RecordInvalid => invalid
      redirect_to new_subscription_path, alert: invalid.record.errors.full_messages[0]
    end
  end

  private

  def subscription_params
    params.require(:subscription).permit(:email)
  end
end

app/views/subscriptions/_form.html.erb
  <!-- ============================================================== -->
<!-- pageheader  -->
<!-- ============================================================== -->
<div class="row">
  <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
    <div class="page-header">
      <h2 class="pageheader-title">E-commerce Product Checkout </h2>
      <p class="pageheader-text">Nulla euismod urna eros, sit amet scelerisque torton lectus vel mauris facilisis faucibus at enim quis massa lobortis rutrum.</p>
      <div class="page-breadcrumb">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">E-coommerce</a></li>
            <li class="breadcrumb-item active" aria-current="page">E-Commerce Product Checkout</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</div>
<!-- ============================================================== -->
<!-- end pageheader  -->
<!-- ============================================================== -->
<div class="row">
  <div class="offset-xl-2 col-xl-8 col-lg-12 col-md-12 col-sm-12 col-12">
    <div class="row">
      <div class="col-md-8">
        <div class="card">
          <div class="card-body text-center">
            <%= t(:presentation) %>
          </div>
          <%= form_tag subscriptions_path, id:"form-subscription" do %>
            <div class="card-body">
              <div class="row">
                <div class="col-md-12 mb-3">
                  <%= label_tag :email%>
                  <%= email_field_tag "subscription[email]",current_user.email, class:"form-control", required: true %>
                </div>
              </div>
            </div>
            <div class="card-body border-top">
              <h5><%= t("preferences") %></h5>
              <%= collection_check_boxes(:subscription, :category_ids, Category.all, :id, :name ) do |b| %>
                <div class="custom-control custom-checkbox">
                  <%=  b.label(:"data-value" => b.value) { b.check_box + b.text } %>
                </div>
              <% end %>
            </div>
            <hr class="mb-4">
            <%= button_tag type: 'submit', class:"btn btn-success btn-block", id:"cmd_save" do %>
              <i class="far fa-paper-plane"></i> <%= t(:subscribe)%>
            <% end %>
          <% end %>
        </div>
      </div>
      <% if !current_user.subscription.nil? %>
        <%= render 'show_subscriptions' %>
      <% end %>
    </div>
  </div>
</div>
<script>
  $(function(){
    var form = $("#form-subscription")
    form.validate({
      errorClass: "text-danger",
      rules: {
        "subscription[email]": {
          required: true,
          email: true
        },
         'subscription[category_ids][]': {
        required: true
        }
      },
      messages:{
          "subscription[email]": {
          required: "Ingrese su correo electrónico",
          email: "Formato de correo inválido"
        },
        'subscription[category_ids][]': "Debes seleccionar una categoría"
      },
       errorPlacement: function (error, element) {
            if (element.attr("type") == "checkbox") {
                 $.notify("Debes seleccionar una categoría", "warn");
            } else {
                  $(element).after(error);
            }
        }
    })
  })
</script>